---
title: 'SQL'
output: html_document
---

## Filtering Rows and Columns

With SQL, you can filter columns with SELECT and rows with WHERE.  Let's look at an example using THE lahman baseball database.  First, we need to load some packages.

```{r warning=FALSE, message=FALSE}
library(Lahman)
library(sqldf)
```

Suppose we want to see the homerun totals for the 1927 Yankees.  We could write the following:

```{r}
query<-"SELECT playerID,yearID,TEAMid,HR FROM Batting
WHERE teamID='NYA' and yearID=1927"
sqldf(query)
```
***

Here are some more examples from class on 9/7/17:

```{r}
query<-"SELECT playerID,teamID,yearID,HR FROM Batting 
WHERE teamID='NYA' and HR>=40"

sqldf(query)
```
***
```{r}
query<-"SELECT playerID,yearID,HR,SO FROM Batting
WHERE HR>40 and SO<60"

sqldf(query)
```
***
```{r}
query<-"SELECT playerID,teamID,yearID,HR FROM Batting
WHERE teamID='PHI' and HR>30 and yearID<=1979 and yearID>=1970"

sqldf(query)
```
***
```{r}
query<-"SELECT playerID,yearID,teamID,HR FROM Batting
WHERE HR>50
ORDER BY HR DESC"

sqldf(query)
```
***
```{r}
query<-"SELECT playerID,yearID,teamID,SO,AB FROM Batting
WHERE SO<10 and AB>=400
ORDER BY SO ASC"

sqldf(query)
```
***
```{r}
query<-"SELECT playerID, sum(HR) FROM Batting
WHERE playerID='ruthba01'
GROUP BY playerID"

sqldf(query)
```
***
```{r}
query<-"SELECT playerID, sum(HR) FROM Batting
GROUP BY playerID
HAVING avg(HR)>30
ORDER BY avg(HR) DESC"

sqldf(query)
```
***
```{r}
query<-"SELECT nameFirst,nameLast,yearID,teamID,HR 
FROM Batting INNER JOIN Master
ON Batting.playerID=Master.playerID
WHERE Batting.playerID='ruthba01'"

sqldf(query)
```
***
